// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6erx_kZrEA4kU0YN8OOoEgmGIBsP_1wM',
    appId: '1:399406767318:web:be3347bfc9e4f6ad507d77',
    messagingSenderId: '399406767318',
    projectId: 'solarsense-bc0e5',
    authDomain: 'solarsense-bc0e5.firebaseapp.com',
    storageBucket: 'solarsense-bc0e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhiu-LZmptANVQi8X6RiFH0t_-WPg3xvs',
    appId: '1:399406767318:android:ac3027e745e4af04507d77',
    messagingSenderId: '399406767318',
    projectId: 'solarsense-bc0e5',
    storageBucket: 'solarsense-bc0e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0q6dT9ejZL77dZNX1E9-f_0WEuoTkAFw',
    appId: '1:399406767318:ios:384b9ff475a36891507d77',
    messagingSenderId: '399406767318',
    projectId: 'solarsense-bc0e5',
    storageBucket: 'solarsense-bc0e5.appspot.com',
    iosBundleId: 'com.example.solarsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0q6dT9ejZL77dZNX1E9-f_0WEuoTkAFw',
    appId: '1:399406767318:ios:64c32f60da8bccf9507d77',
    messagingSenderId: '399406767318',
    projectId: 'solarsense-bc0e5',
    storageBucket: 'solarsense-bc0e5.appspot.com',
    iosBundleId: 'com.example.solarsense.RunnerTests',
  );
}
